---
title: "rm013- Effective Visualizations"
author: "Racquelle Sabrina Mangahas"
date: "15/10/2019"
output:
  html_document: default
  pdf_document: default
---

# Effective Visualizations

Now that you know how to create graphics and visualizations in R, you are armed with powerful tools for scientific computing and analysis. With this power also comes great responsibility. Effective visualizations is an incredibly important aspect of scientific research and communication. There have been several books (see references) written about these principles. In class today we will be going through several case-studies trying to develop some expertise into making effective visualizations. 

## Worksheet

**The worksheet questions for today are embedded into the class notes.**

You can download this Rmd file [here](https://github.com/STAT545-UBC/Classroom/blob/master/cm013.Rmd)

Note, there will be very little coding in-class today, but I've given you plenty of exercises in the form of a supplemental worksheet (linked at the bottom of this page) to practice with after class is over.

## Resources

1. [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/introduction.html) by Claus Wilke.

1. [Visualization Analysis and Design](https://www-taylorfrancis-com.ezproxy.library.ubc.ca/books/9780429088902) by Tamara Munzner.

1. [STAT545.com - Effective Graphics](https://stat545.com/effective-graphs.html) by Jenny Bryan.

1. [ggplot2 book](https://ggplot2-book.org) by Hadley Wickam.

1. [Callingbull.org](https://callingbull.org/tools.html) by Carl T. Bergstrom and Jevin West.

## Part 1: Warm-up and pre-test [20 mins]

### Warmup:

Write some notes here about what "effective visualizations" means to you. Think of elements of good graphics and plots that you have seen - what makes them good or bad? Write 3-5 points.

1. Colourful (rather then them just being black and white)
1. Simple and clean (not too much going on)
1. Not all over the place, as in easy to understand and follow what they are trying to portray
1. Labelling of the graph/plots
1.

### CQ01: Weekly hours for full-time employees

> Question: Evaluate the strength of the claim based on the data: "German workers are more motivated and work more hours than workers in other EU nations."
>
> Very strong, strong, weak, very week, do not know

- <<Weak; I'm not sure about equating 'motivation' to working more hours. Also the number of hours they found (40.4) isn't much of a difference compared to the other EU nations that still averaged around ~39 hours per week. The bars on the graph can be misleading as it shows that Germany works "MORE" hours then the ones below. Don't have much of an idea of the variance/standard deviation of the results, just given the average. Authors portrayed graph in such a way that supports their conclusion. Grid lines distract from overall message, and also the x-axis did not start at 0hrs but rather 36. Don't really need grid lines AND numbers at the end, redundant. In reality the fixed graph shows there isn't much difference between the nations; also that there isn't much difference of Germany compared to others.  >>

- Main takeaway: Summarize the main takeaway from this question/discussion here

### CQ02: Average Global Temperature by year

> Question: For the years this temperature data is displayed, is there an appreciable increase in temperature?
> 
> Yes, No, Do not know

- <<Don't know, I would say that based on this graph, it doesn't appear to be an appreciable increase in temperature. The y-axis is very broad such that you can really see the close-up changes of the temperature (i.e. fluctuations throughout the year). Also the x-axis you don't know what time period that they took their data from. Maybe if there was more of a close up of the y-axis you can see the changes more so, but that also depends on what 'appreciable' increase would be defined as. New graph: appropriate y scale you can see how bad 2 degree increase is; the other plot may be to show that there 'isn't much of a warming effect'. THUS not always necessary to start the y-axis at 0 or not. >>

- Main takeaway: Summarize the main takeaway from this question/discussion here

### CQ03: Gun deaths in Florida

> Question: Evaluate the strength of the claim based on the data: “Soon after this legislation was passed, gun deaths sharply declined."
>
> Very strong, strong, weak, very week, do not know

- <Very weak, I would say that after the "Stand Your Ground" law was created there was an increase of gun-related deaths (almost to the 873 count, before being decreased but it still isn't different than before the law was made). The flipping of the y-axis really misleads you into thinking that there was a decrease rather than increase. Also the fact that they put the red colour may hinder interpretation. >>

- Main takeaway: Summarize the main takeaway from this question/discussion here

## Part 2: Extracting insight from visualizations  [20 mins]

Great resource for selecting the right plot: https://www.data-to-viz.com/ ; encourage you all to consult it when choosing to visualize data.

### Case Study 1: Context matters

### Case Study 2: A case for pie charts

## Part 3: Principles of effective visualizations [20 mins]

We will be filling these principles in together as a class

1. 
1. 
1. 
1. 
1. 

### Make a great plot worse

Instructions: Here is a code chunk that shows an effective visualization. First, copy this code chunk into a new cell. Then, modify it to purposely make this chart "bad" by breaking the principles of effective visualization above. Your final chart still needs to run/compile and it should still produce a plot. 

How many of the principles did you manage to break?

## Plotly demo [10 mins]

Did you know that you can make interactive graphs and plots in R using the plotly library? We will show you a demo of what plotly is and why it's useful, and then you can try converting a static ggplot graph into an interactive plotly graph.

This is a preview of what we'll be doing in STAT 547 - making dynamic and interactive dashboards using R!

# For some reason the error message kept showing for the code chunk below, I did complete the coding though as I attended class. 

install.packages('plotly')



library(tidyverse)
library(gapminder)
library(plotly)

p <- ggplot(gapminder, aes(x=gdpPercap, y=lifeExp, colour=continent)) +
  geom_point()
p

#make interactive
p %>% ggplotly()

#plot_ly syntax
p<- gapminder %>% 
  plot_ly(x=~gpPercap, 
          y= ~lifeExp, 
          colour= ~continent, 
          type= 'scatter', 
          mode= 'markers') #line graph then do 'lines'

Sys.setenv("plotly_username"="racquellem")  #transfer to plotly
Sys.setenc("plotly_api_key"= "get this from on the website, settings-> API")

api_create(p, filename='cm013-plotly- example')




## Supplemental worksheet (Optional)

You are highly encouraged to the cm013 supplemental exercises worksheet. It is a great guide that will take you through Scales, Colours, and Themes in ggplot. There is also a short guided activity showing you how to make a ggplot interactive using plotly.

Supplemental Rmd file here](https://raw.githubusercontent.com/STAT545-UBC/Classroom/master/tutorials/cm013-supplemental.Rmd)